GCC = g++

all: base cubes markup sequence

base:
	$(GCC) base.cpp -o base.out
	./base.out

cubes:
	$(GCC) cubes.cpp -o cubes.out
	./cubes.out

markup:
	$(GCC) markup.cpp -o markup.out
	./markup.out

sequence:
	$(GCC) sequence.cpp -o sequence.out
	./sequence.out

clean:
	rm -f *.out
